### ISSUE TITLE
`ReferenceError: location is not defined` with SvelteKit SSR

### ISSUE THREAD

**Issue by ixxie** [nytimes/rd-bundler-3d-plugins#19]
It seems SSR in SvelteKit breaks [vite-plugin-gltf](https://github.com/nytimes/rd-bundler-3d-plugins/), yielding the errors such as the following:

```
ReferenceError: location is not defined
    at file:///home/ixxie/repos/sveltekit-gltf/.svelte-kit/output/server/entries/pages/_page.svelte.js:16468:55
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
    at async Module.component (file:///home/ixxie/repos/sveltekit-gltf/.svelte-kit/output/server/nodes/2.js:4:39)
    at async Promise.all (index 1)
    at async render_response (file:///home/ixxie/repos/sveltekit-gltf/.svelte-kit/output/server/index.js:1206:19)
    at async render_page (file:///home/ixxie/repos/sveltekit-gltf/.svelte-kit/output/server/index.js:1752:12)
    at async resolve (file:///home/ixxie/repos/sveltekit-gltf/.svelte-kit/output/server/index.js:2436:22)
    at async respond (file:///home/ixxie/repos/sveltekit-gltf/.svelte-kit/output/server/index.js:2327:22)
 ```
 
 Minimal reproduction is available [in this repository](https://github.com/seedling-life/sveltekit-gltf).
 
 Relevant discussions:
   - https://github.com/nytimes/rd-bundler-3d-plugins/issues/14
   - https://github.com/nytimes/rd-bundler-3d-plugins/pull/17

**Comment by ixxie** [comment]
It seems the other issue got a response from Rich Harris himself, and he identifies the source of the issue within the plugin: https://github.com/sveltejs/kit/issues/9000#issuecomment-1426820849
